language: cpp

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

dist: xenial

compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - make test
