language: cpp

os:
  - linux
    addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
  - osx

dist: xenial

compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - make test
