version: 2
jobs:
  linux_gcc:
    docker:
      - image: ubuntu:19.04
    steps:
      - run: apt-get update && apt-get install -y git
      - checkout
      - run: apt-get install -y gcc g++
      - run: make CXX=g++ CXX_STANDARD=c++2a test
  linux_clang:
    docker:
      - image: ubuntu:19.04
    steps:
      - run: apt-get update && apt-get install -y git
      - checkout
      - run: apt-get install -y clang
      - run: make CXX=clang++ CXX_STANDARD=c++2a test
  macos_gcc:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: brew install gcc@8
      - run: make CXX=/usr/local/bin/g++-8 CXX_STANDARD=c++2a test
  macos_clang:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: make CXX=clang++ CXX_STANDARD=c++2a test
workflows:
  version: 2
  ci:
    jobs:
      - linux_gcc
      - linux_clang
      - macos_gcc
      - macos_clang
